name: yourbreak
description: "Timer app made in Flutter"
repository: https://github.com/Katanasoldier/YourBreak
homepage: https://github.com/Katanasoldier/YourBreak
issue_tracker: https://github.com/Katanasoldier/YourBreak/issues

publish_to: 'none'
version: 1.0.0

environment:
  flutter: ^3.32.7
  sdk: '>=3.7.2'

platforms:
  windows:

dependencies:
  audioplayers: ^6.5.0
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  page_transition: ^2.2.1
  path_provider: ^2.1.2
  shared_preferences: ^2.5.3
  window_manager: ^0.4.3

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  icons_launcher: ^3.0.2

icons_launcher:
  image_path: "assets/ico/launcher_logo.png"
  platforms:
    windows:
      enable: true

flutter:

  uses-material-design: true

  fonts:
    - family: Inria Sans
      fonts:
        - asset: fonts/InriaSans-Regular.ttf
          weight: 400
        - asset: fonts/InriaSans-Bold.ttf
          weight: 700

  assets:
  - assets/svg/
  - assets/presets.json
  - assets/audio/timer_up/timer_up_1.mp3