name: yourbreak
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  window_manager: ^0.4.3
  auto_size_text: ^3.0.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  shared_preferences: ^2.5.3
  audioplayers: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:

  fonts:
  - family: Inria Sans
    fonts:
      - asset: fonts/InriaSans-Regular.ttf
        weight: 400
      - asset: fonts/InriaSans-Bold.ttf
        weight: 700

  assets:
  - assets/svg/controlbuttonsframe.svg
  - assets/svg/stopwatch.svg
  - assets/svg/minimize.svg
  - assets/svg/close.svg
  - assets/svg/plus.svg
  - assets/svg/folder.svg
  - assets/svg/pencil.svg
  - assets/svg/cog.svg
  - assets/svg/multipleCogs.svg
  - assets/svg/wrench.svg
  - assets/svg/squareedit.svg
  - assets/svg/x.svg
  - assets/presets.json

  - assets/audio/timer_up/timer_up_1.mp3

  uses-material-design: true